##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [3.13.0-B3] date: [Wed Feb 02 22:44:56 CST 2022]
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2022-12-01 - update for GD32F470
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = gd32f4xx_project


######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -Og


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

#######################################
# Firmware Library and Utilities
#######################################
# 注释：这些路径在实际项目中可能不存在，需要根据项目结构调整
# GD32_CMSIS_LIBRARY_DIR = ../../../GD32F4xx_Firmware_Library/CMSIS
# GD32_SP_LIBRARY_DIR = ../../../GD32F4xx_Firmware_Library/GD32F4xx_standard_peripheral
# GD32_UTILITIES_DIR = ../../Utilities

######################################
# source
######################################
# C sources - 由create_makefile.py脚本自动扫描生成所有.c文件路径
C_SOURCES +=  \
./Drivers/CMSIS/GD/GD32F4xx/Source/system_gd32f4xx.c \
./Drivers/CMSIS/GD/GD32F4xx/Source/syscalls.c \
./Drivers/GD32F4xx_standard_peripheral/Source/gd32f4xx_dbg.c \
./Drivers/GD32F4xx_standard_peripheral/Source/gd32f4xx_i2c.c \
./Drivers/GD32F4xx_standard_peripheral/Source/gd32f4xx_rcu.c \
./Drivers/GD32F4xx_standard_peripheral/Source/gd32f4xx_dci.c \
./Drivers/GD32F4xx_standard_peripheral/Source/gd32f4xx_fwdgt.c \
./Drivers/GD32F4xx_standard_peripheral/Source/gd32f4xx_ipa.c \
./Drivers/GD32F4xx_standard_peripheral/Source/gd32f4xx_gpio.c \
./Drivers/GD32F4xx_standard_peripheral/Source/gd32f4xx_rtc.c \
./Drivers/GD32F4xx_standard_peripheral/Source/gd32f4xx_timer.c \
./Drivers/GD32F4xx_standard_peripheral/Source/gd32f4xx_iref.c \
./Drivers/GD32F4xx_standard_peripheral/Source/gd32f4xx_pmu.c \
./Drivers/GD32F4xx_standard_peripheral/Source/gd32f4xx_spi.c \
./Drivers/GD32F4xx_standard_peripheral/Source/gd32f4xx_sdio.c \
./Drivers/GD32F4xx_standard_peripheral/Source/gd32f4xx_ctc.c \
./Drivers/GD32F4xx_standard_peripheral/Source/gd32f4xx_fmc.c \
./Drivers/GD32F4xx_standard_peripheral/Source/gd32f4xx_tli.c \
./Drivers/GD32F4xx_standard_peripheral/Source/gd32f4xx_trng.c \
./Drivers/GD32F4xx_standard_peripheral/Source/gd32f4xx_can.c \
./Drivers/GD32F4xx_standard_peripheral/Source/gd32f4xx_misc.c \
./Drivers/GD32F4xx_standard_peripheral/Source/gd32f4xx_crc.c \
./Drivers/GD32F4xx_standard_peripheral/Source/gd32f4xx_enet.c \
./Drivers/GD32F4xx_standard_peripheral/Source/gd32f4xx_syscfg.c \
./Drivers/GD32F4xx_standard_peripheral/Source/gd32f4xx_exmc.c \
./Drivers/GD32F4xx_standard_peripheral/Source/gd32f4xx_adc.c \
./Drivers/GD32F4xx_standard_peripheral/Source/gd32f4xx_dac.c \
./Drivers/GD32F4xx_standard_peripheral/Source/gd32f4xx_usart.c \
./Drivers/GD32F4xx_standard_peripheral/Source/gd32f4xx_dma.c \
./Drivers/GD32F4xx_standard_peripheral/Source/gd32f4xx_exti.c \
./Drivers/GD32F4xx_standard_peripheral/Source/gd32f4xx_wwdgt.c \
./Core/src/systick.c \
./Core/src/main.c \
./Core/src/device_init.c \
./Core/src/adc_driver.c \
./Core/src/com_driver.c \
./Core/src/fft_phasor_task.c \
./Core/src/gd32f4xx_it.c \
./Drivers/FreeRTOS/source/croutine.c \
./Drivers/FreeRTOS/source/event_groups.c \
./Drivers/FreeRTOS/source/list.c \
./Drivers/FreeRTOS/source/queue.c \
./Drivers/FreeRTOS/source/stream_buffer.c \
./Drivers/FreeRTOS/source/tasks.c \
./Drivers/FreeRTOS/source/timers.c \
./Drivers/FreeRTOS/portable/MemMang/heap_4.c \
./Drivers/FreeRTOS/portable/GCC/ARM_CM4F/port.c \
./Drivers/CMSIS/DSP/Source/TransformFunctions/TransformFunctions.c \
./Drivers/CMSIS/DSP/Source/FastMathFunctions/FastMathFunctions.c \
./Drivers/CMSIS/DSP/Source/CommonTables/CommonTables.c

# ASM sources - 由create_makefile.py脚本自动扫描生成所有.s文件路径
ASM_SOURCES += 

# ASM sources (.S files) - 由create_makefile.py脚本自动扫描生成所有.S文件路径  
ASMM_SOURCES +=  \
./startup_gd32f450_470.S

#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
# GCC_PATH = /Applications/ARM/bin

ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m4

# fpu
FPU = -mfpu=fpv4-sp-d16

# float-abi
FLOAT-ABI = -mfloat-abi=hard

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DUSE_STDPERIPH_DRIVER \
-DGD32F4xx \
-DGD32F470


# AS includes
AS_INCLUDES = 

# C includes - 由create_makefile.py脚本自动扫描生成所有头文件目录
C_INCLUDES +=  \
-I./Core/inc \
-I./Drivers/CMSIS \
-I./Drivers/CMSIS/GD/GD32F4xx/Include \
-I./Drivers/GD32F4xx_standard_peripheral/Include \
-I./Drivers/FreeRTOS/include \
-I./Drivers/FreeRTOS/portable/GCC/ARM_CM4F \
-I./Drivers/CMSIS/DSP/Include

# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS += $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script - 由create_makefile.py脚本自动扫描生成链接脚本路径
LDSCRIPT = ./gd32f4xx_flash.ld

# libraries
LIBS = -lc -lm -lnosys 
LIBDIR = 
LDFLAGS = $(MCU) -specs=nano.specs -specs=nosys.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of objects - 从C源文件生成目标文件列表
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects - 从.s汇编文件生成目标文件列表
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))
# list of ASMM program objects - 从.S汇编文件生成目标文件列表
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASMM_SOURCES:.S=.o)))
vpath %.S $(sort $(dir $(ASMM_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR) 
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@
$(BUILD_DIR)/%.o: %.S Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	
	
$(BUILD_DIR):
	mkdir $@		

#######################################
# clean up
#######################################
clean:
	-rm -fR $(BUILD_DIR)
  
#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***